spring:
  application:
    name: devy-board-api
  datasource:
    url: jdbc:mysql://root:UeqBfbENteDmsqjaWTOCAjzBQbBmitou@maglev.proxy.rlwy.net:12007/railway
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always  # Ensures schema.sql is executed on startup